apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lr-app-ingress
  namespace: lr-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    
spec:
  rules:
    - host: <your.domain.example>   # replace or remove rule to use default host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lr-app-svc
                port:
                  number: 80
